name: Deploy to fly.io

on:
  push:
    branches:
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install all dependencies
        run: npm install

      - name: Add .env var for login access token
        run: echo ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} >> .env

      - name: Add .env var for login refresh token
        run: echo REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }} >> .env

      - name: Add .env var for database url
        run: echo DBURL=${{ secrets.DBURL }} >> .env
      
      - name: Check for .env file
        run: cat .env

      - name: Run the API
        run: npm start &

      # - name: Test the API
      #   run: curl http://localhost:3000/ | grep "DopeGood"
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only